/*
 * Copyright 2010-2016 JetBrains s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.jetbrains.kotlin.gradle.plugin

import com.android.build.gradle.BaseExtension
import org.gradle.api.GradleException
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.artifacts.Configuration
import org.gradle.api.artifacts.ProjectDependency
import org.gradle.api.file.SourceDirectorySet
import org.gradle.api.plugins.JavaPluginConvention
import org.gradle.api.tasks.SourceSet
import org.gradle.api.tasks.SourceSetContainer
import org.jetbrains.kotlin.gradle.tasks.AbstractKotlinCompile

abstract class KotlinPlatformPluginBase(protected val platformName: String) : Plugin<Project> {
    companion object {
        @JvmStatic
        protected inline fun <reified T : Plugin<*>> Project.applyPlugin() {
            pluginManager.apply(T::class.java)
        }
    }
}

open class KotlinPlatformCommonPlugin : KotlinPlatformPluginBase("common") {
    override fun apply(project: Project) {
        project.applyPlugin<KotlinCommonPluginWrapper>()
    }
}

const val EXPECTED_BY_CONFIG_NAME = "expectedBy"

const val IMPLEMENT_CONFIG_NAME = "implement"
const val IMPLEMENT_DEPRECATION_WARNING = "The '$IMPLEMENT_CONFIG_NAME' configuration is deprecated and will be removed. " +
                                          "Use '$EXPECTED_BY_CONFIG_NAME' instead."

open class KotlinPlatformImplementationPluginBase(platformName: String) : KotlinPlatformPluginBase(platformName) {
    private val commonProjects = arrayListOf<Project>()
    private val platformKotlinTasksBySourceSetName = hashMapOf<String, AbstractKotlinCompile<*>>()

    override fun apply(project: Project) {
        project.tasks.filterIsInstance<AbstractKotlinCompile<*>>().associateByTo(platformKotlinTasksBySourceSetName) { it.sourceSetName }

        val implementConfig = project.configurations.create(IMPLEMENT_CONFIG_NAME)
        val expectedByConfig = project.configurations.create(EXPECTED_BY_CONFIG_NAME)

        implementConfig.dependencies.whenObjectAdded {
            if (!implementConfigurationIsUsed) {
                implementConfigurationIsUsed = true
                project.logger.kotlinWarn(IMPLEMENT_DEPRECATION_WARNING)
            }
        }

        listOf(implementConfig, expectedByConfig).forEach { config ->
            config.isTransitive = false

            config.dependencies.whenObjectAdded { dep ->
                if (dep is ProjectDependency) {
                    addCommonProject(dep.dependencyProject, project)

                    // Needed for the projects that depend on this one to recover the common module sources through
                    // the transitive dependency (also, it will be added to the POM generated by Gradle):
                    project.configurations.getByName("compile").dependencies.add(dep)
                }
                else {
                    throw GradleException("$project '${config.name}' dependency is not a project: $dep")
                }
            }
        }

        val incrementalMultiplatform = PropertiesProvider(project).incrementalMultiplatform ?: true
        project.afterEvaluate {
            project.tasks.withType(AbstractKotlinCompile::class.java).all {
                if (it.incremental && !incrementalMultiplatform) {
                    project.logger.debug("IC is turned off for task '${it.path}' because multiplatform IC is not enabled")
                }
                it.incremental = it.incremental && incrementalMultiplatform
            }
        }
    }

    private var implementConfigurationIsUsed = false

    private fun platformImplementationConfigName(platform: String) = "platform${platform.capitalize()}Implementations"

    private fun automaticPlatformDependenciesConfigName(sourceSetName: String) = "autoconfigured${sourceSetName.capitalize()}Dependencies"

    private fun addCommonProject(commonProject: Project, platformProject: Project) {
        commonProjects.add(commonProject)

        commonProject.whenEvaluated {
            if (!commonProject.pluginManager.hasPlugin("kotlin-platform-common")) {
                throw GradleException(
                        "Platform project $platformProject has an " +
                        "'$EXPECTED_BY_CONFIG_NAME'${if (implementConfigurationIsUsed) "/'$IMPLEMENT_CONFIG_NAME'" else ""} " +
                        "dependency to non-common project $commonProject")
            }

            commonProject.sourceSets.all { commonSourceSet ->
                // todo: warn if not found
                addCommonSourceSetToPlatformSourceSet(commonSourceSet, platformProject)
            }

            val platformImplementationConfigName = platformImplementationConfigName(platformName)
            commonProject.configurations.maybeCreate(platformImplementationConfigName)
            commonProject.dependencies.add(platformImplementationConfigName, platformProject)
        }

        // Single variable for all source sets below,
        // lazy to prevent it from traversing the modules before they are evaluated
        val commonModuleDependencies = lazy {
            getCommonModuleDependencies(commonProject)
        }

        platformProject.afterEvaluate {
            val mainSourceSet = platformProject.sourceSets.getByName("main")
            val configurationToAddDeps = platformProject.configurations.getAt("implementation")
            val configurationToCheckDeps =
                mainSourceSet.compileClasspath as? Configuration
                        ?: platformProject.configurations.findByName(mainSourceSet.compileClasspathConfigurationName)
                        ?: configurationToAddDeps

            setUpPlatformModuleDependencies(
                platformProject,
                mainSourceSet,
                configurationToCheckDeps,
                configurationToAddDeps,
                commonModuleDependencies
            )
        }
    }

    private fun getCommonModuleDependencies(from: Project): List<Project> {

        fun getCompileProjectDependencies(project: Project) =
            project.configurations.findByName("compileClasspath")?.allDependencies
                .orEmpty()
                .filterIsInstance<ProjectDependency>()
                .map { it.dependencyProject }

        return generateSequence(listOf(from)) { prev -> prev.flatMap { getCompileProjectDependencies(it) } }
            .drop(1)
            .takeWhile { it.isNotEmpty() }
            .flatten()
            .toList()
    }

    //TODO adapt for Native
    private val platformDisplayName = platformName.toUpperCase()

    private fun setUpPlatformModuleDependencies(
        platformProject: Project,
        sourceSet: SourceSet,
        configurationToCheck: Configuration,
        defaultConfigurationToAdd: Configuration,
        commonModuleDependencies: Lazy<List<Project>>
    ) {
        // Workaround: with configure-on-demand, we still need to evaluate all projects. This forces them to evaluate:
        platformProject.rootProject.allprojects { project ->
            platformProject.rootProject.evaluationDependsOn(project.path)
        }

        defaultConfigurationToAdd.withDependencies {
            commonModuleDependencies.value.forEach { commonModule ->
                val platformImplDeps =
                    commonModule.configurations.findByName(platformImplementationConfigName(platformName))

                val platformImplProjectDeps =
                    platformImplDeps?.dependencies.orEmpty().filterIsInstance<ProjectDependency>()

                val platformImplProjectPaths = platformImplProjectDeps.map { it.dependencyProject.path }

                val thisProjectDependsOnImpl = configurationToCheck.allDependencies.any { dep ->
                    dep is ProjectDependency && dep.dependencyProject.path in platformImplProjectPaths
                }

                when {
                    thisProjectDependsOnImpl -> Unit
                    platformImplProjectDeps.isEmpty() -> {
                        println(
                            "No $platformDisplayName platform module found for the common dependency ${commonModule.path} of " +
                                    "platform module ${platformProject.path}. Please make sure there is a ${platformDisplayName} " +
                                    "platform implementation and " +
                                    "the project containing it is evaluated at the moment of the dependency resolution."
                        )
                    }
                    platformImplProjectDeps.size == 1 -> {
                        val singlePlatformImpl = platformImplProjectDeps.single().dependencyProject
                        platformProject.logger.kotlinInfo("Found a single ${platformDisplayName} platform implementation ${singlePlatformImpl.path} " +
                                                                  "for common dependency ${commonModule.path}. " +
                                                                  "Adding it to ${defaultConfigurationToAdd}.")
                        platformProject.dependencies.add(defaultConfigurationToAdd.name, singlePlatformImpl)
                    }
                    else -> { // platformImplProjectDeps.size > 1
                        platformProject.logger.kotlinWarn(
                            "A platform module ${platformProject.path} does not explicitly depend on a ${platformDisplayName} platform implementation " +
                                    "of its common dependency ${commonModule.path}. " +
                                    "Please manually choose one of the platform modules and specify the dependency for ${sourceSet.name}:" +
                                    platformImplProjectPaths.joinToString("\n") { " * $it" }
                        )
                    }
                }
            }
        }
    }

    protected open fun addCommonSourceSetToPlatformSourceSet(commonSourceSet: SourceSet, platformProject: Project) {
        val platformTask = platformKotlinTasksBySourceSetName[commonSourceSet.name]
        commonSourceSet.kotlin!!.srcDirs.forEach { platformTask?.source(it) }
    }

    protected val SourceSet.kotlin: SourceDirectorySet?
        get() {
            // Access through reflection, because another project's KotlinSourceSet might be loaded
            // by a different class loader:
            val convention = (getConvention("kotlin") ?: getConvention("kotlin2js")) ?: return null
            val kotlinSourceSetIface = convention.javaClass.interfaces.find { it.name == KotlinSourceSet::class.qualifiedName }
            val getKotlin = kotlinSourceSetIface?.methods?.find { it.name == "getKotlin" } ?: return null
            return getKotlin(convention) as? SourceDirectorySet
        }

    companion object {
        @JvmStatic
        protected fun <T> Project.whenEvaluated(fn: Project.() -> T) {
            if (state.executed) {
                fn()
            }
            else {
                afterEvaluate { it.fn() }
            }
        }
    }
}

open class KotlinPlatformAndroidPlugin : KotlinPlatformImplementationPluginBase("android") {
    override fun apply(project: Project) {
        project.applyPlugin<KotlinAndroidPluginWrapper>()
        super.apply(project)
    }

    override fun addCommonSourceSetToPlatformSourceSet(commonSourceSet: SourceSet, platformProject: Project) {
        val androidExtension = platformProject.extensions.getByName("android") as BaseExtension
        val androidSourceSet = androidExtension.sourceSets.findByName(commonSourceSet.name) ?: return
        val kotlinSourceSet = androidSourceSet.getConvention(KOTLIN_DSL_NAME) as? KotlinSourceSet ?: return
        kotlinSourceSet.kotlin.source(commonSourceSet.kotlin!!)
    }
}

open class KotlinPlatformJvmPlugin : KotlinPlatformImplementationPluginBase("jvm") {
    override fun apply(project: Project) {
        project.applyPlugin<KotlinPluginWrapper>()
        super.apply(project)
    }
}

open class KotlinPlatformJsPlugin : KotlinPlatformImplementationPluginBase("js") {
    override fun apply(project: Project) {
        project.applyPlugin<Kotlin2JsPluginWrapper>()
        super.apply(project)
    }
}

private val Project.sourceSets: SourceSetContainer
    get() = convention.getPlugin(JavaPluginConvention::class.java).sourceSets
