// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

public interface ActualOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jetbrains.kotlin.backend.common.serialization.proto.Actual)
    org.jetbrains.kotlin.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required int64 actual_symbol = 1;</code>
   *
   * <pre>
   *    required int32 actual_symbol = 1;
   * </pre>
   */
  boolean hasActualSymbol();
  /**
   * <code>required int64 actual_symbol = 1;</code>
   *
   * <pre>
   *    required int32 actual_symbol = 1;
   * </pre>
   */
  long getActualSymbol();

  /**
   * <code>required int64 expect_symbol = 2;</code>
   *
   * <pre>
   *    required int32 expect_symbol = 2;
   * </pre>
   */
  boolean hasExpectSymbol();
  /**
   * <code>required int64 expect_symbol = 2;</code>
   *
   * <pre>
   *    required int32 expect_symbol = 2;
   * </pre>
   */
  long getExpectSymbol();
}