// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

public interface ClassAndPackageIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId)
    org.jetbrains.kotlin.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated int32 package_fq_name = 1;</code>
   */
  java.util.List<java.lang.Integer> getPackageFqNameList();
  /**
   * <code>repeated int32 package_fq_name = 1;</code>
   */
  int getPackageFqNameCount();
  /**
   * <code>repeated int32 package_fq_name = 1;</code>
   */
  int getPackageFqName(int index);

  /**
   * <code>repeated int32 class_fq_name = 2;</code>
   */
  java.util.List<java.lang.Integer> getClassFqNameList();
  /**
   * <code>repeated int32 class_fq_name = 2;</code>
   */
  int getClassFqNameCount();
  /**
   * <code>repeated int32 class_fq_name = 2;</code>
   */
  int getClassFqName(int index);
}