// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

/**
 * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId}
 */
public final class ClassAndPackageId extends
    org.jetbrains.kotlin.protobuf.GeneratedMessageLite implements
    // @@protoc_insertion_point(message_implements:org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId)
    ClassAndPackageIdOrBuilder {
  // Use ClassAndPackageId.newBuilder() to construct.
  private ClassAndPackageId(org.jetbrains.kotlin.protobuf.GeneratedMessageLite.Builder builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private ClassAndPackageId(boolean noInit) { this.unknownFields = org.jetbrains.kotlin.protobuf.ByteString.EMPTY;}

  private static final ClassAndPackageId defaultInstance;
  public static ClassAndPackageId getDefaultInstance() {
    return defaultInstance;
  }

  public ClassAndPackageId getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final org.jetbrains.kotlin.protobuf.ByteString unknownFields;
  private ClassAndPackageId(
      org.jetbrains.kotlin.protobuf.CodedInputStream input,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    org.jetbrains.kotlin.protobuf.ByteString.Output unknownFieldsOutput =
        org.jetbrains.kotlin.protobuf.ByteString.newOutput();
    org.jetbrains.kotlin.protobuf.CodedOutputStream unknownFieldsCodedOutput =
        org.jetbrains.kotlin.protobuf.CodedOutputStream.newInstance(
            unknownFieldsOutput, 1);
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              packageFqName_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            packageFqName_.add(input.readInt32());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
              packageFqName_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              packageFqName_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 16: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              classFqName_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000002;
            }
            classFqName_.add(input.readInt32());
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
              classFqName_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000002;
            }
            while (input.getBytesUntilLimit() > 0) {
              classFqName_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        packageFqName_ = java.util.Collections.unmodifiableList(packageFqName_);
      }
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        classFqName_ = java.util.Collections.unmodifiableList(classFqName_);
      }
      try {
        unknownFieldsCodedOutput.flush();
      } catch (java.io.IOException e) {
      // Should not happen
      } finally {
        unknownFields = unknownFieldsOutput.toByteString();
      }
      makeExtensionsImmutable();
    }
  }
  public static org.jetbrains.kotlin.protobuf.Parser<ClassAndPackageId> PARSER =
      new org.jetbrains.kotlin.protobuf.AbstractParser<ClassAndPackageId>() {
    public ClassAndPackageId parsePartialFrom(
        org.jetbrains.kotlin.protobuf.CodedInputStream input,
        org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
      return new ClassAndPackageId(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public org.jetbrains.kotlin.protobuf.Parser<ClassAndPackageId> getParserForType() {
    return PARSER;
  }

  public static final int PACKAGE_FQ_NAME_FIELD_NUMBER = 1;
  private java.util.List<java.lang.Integer> packageFqName_;
  /**
   * <code>repeated int32 package_fq_name = 1;</code>
   */
  public java.util.List<java.lang.Integer>
      getPackageFqNameList() {
    return packageFqName_;
  }
  /**
   * <code>repeated int32 package_fq_name = 1;</code>
   */
  public int getPackageFqNameCount() {
    return packageFqName_.size();
  }
  /**
   * <code>repeated int32 package_fq_name = 1;</code>
   */
  public int getPackageFqName(int index) {
    return packageFqName_.get(index);
  }

  public static final int CLASS_FQ_NAME_FIELD_NUMBER = 2;
  private java.util.List<java.lang.Integer> classFqName_;
  /**
   * <code>repeated int32 class_fq_name = 2;</code>
   */
  public java.util.List<java.lang.Integer>
      getClassFqNameList() {
    return classFqName_;
  }
  /**
   * <code>repeated int32 class_fq_name = 2;</code>
   */
  public int getClassFqNameCount() {
    return classFqName_.size();
  }
  /**
   * <code>repeated int32 class_fq_name = 2;</code>
   */
  public int getClassFqName(int index) {
    return classFqName_.get(index);
  }

  private void initFields() {
    packageFqName_ = java.util.Collections.emptyList();
    classFqName_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(org.jetbrains.kotlin.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    for (int i = 0; i < packageFqName_.size(); i++) {
      output.writeInt32(1, packageFqName_.get(i));
    }
    for (int i = 0; i < classFqName_.size(); i++) {
      output.writeInt32(2, classFqName_.get(i));
    }
    output.writeRawBytes(unknownFields);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < packageFqName_.size(); i++) {
        dataSize += org.jetbrains.kotlin.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(packageFqName_.get(i));
      }
      size += dataSize;
      size += 1 * getPackageFqNameList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < classFqName_.size(); i++) {
        dataSize += org.jetbrains.kotlin.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(classFqName_.get(i));
      }
      size += dataSize;
      size += 1 * getClassFqNameList().size();
    }
    size += unknownFields.size();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId parseFrom(
      org.jetbrains.kotlin.protobuf.ByteString data)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId parseFrom(
      org.jetbrains.kotlin.protobuf.ByteString data,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId parseFrom(byte[] data)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId parseFrom(
      byte[] data,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId parseFrom(
      java.io.InputStream input,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId parseDelimitedFrom(
      java.io.InputStream input,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId parseFrom(
      org.jetbrains.kotlin.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId parseFrom(
      org.jetbrains.kotlin.protobuf.CodedInputStream input,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  /**
   * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId}
   */
  public static final class Builder extends
      org.jetbrains.kotlin.protobuf.GeneratedMessageLite.Builder<
        org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId, Builder>
      implements
      // @@protoc_insertion_point(builder_implements:org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId)
      org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageIdOrBuilder {
    // Construct using org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      packageFqName_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      classFqName_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId getDefaultInstanceForType() {
      return org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId.getDefaultInstance();
    }

    public org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId build() {
      org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId buildPartial() {
      org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId result = new org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        packageFqName_ = java.util.Collections.unmodifiableList(packageFqName_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.packageFqName_ = packageFqName_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        classFqName_ = java.util.Collections.unmodifiableList(classFqName_);
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.classFqName_ = classFqName_;
      return result;
    }

    public Builder mergeFrom(org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId other) {
      if (other == org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId.getDefaultInstance()) return this;
      if (!other.packageFqName_.isEmpty()) {
        if (packageFqName_.isEmpty()) {
          packageFqName_ = other.packageFqName_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensurePackageFqNameIsMutable();
          packageFqName_.addAll(other.packageFqName_);
        }
        
      }
      if (!other.classFqName_.isEmpty()) {
        if (classFqName_.isEmpty()) {
          classFqName_ = other.classFqName_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureClassFqNameIsMutable();
          classFqName_.addAll(other.classFqName_);
        }
        
      }
      setUnknownFields(
          getUnknownFields().concat(other.unknownFields));
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        org.jetbrains.kotlin.protobuf.CodedInputStream input,
        org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<java.lang.Integer> packageFqName_ = java.util.Collections.emptyList();
    private void ensurePackageFqNameIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        packageFqName_ = new java.util.ArrayList<java.lang.Integer>(packageFqName_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int32 package_fq_name = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getPackageFqNameList() {
      return java.util.Collections.unmodifiableList(packageFqName_);
    }
    /**
     * <code>repeated int32 package_fq_name = 1;</code>
     */
    public int getPackageFqNameCount() {
      return packageFqName_.size();
    }
    /**
     * <code>repeated int32 package_fq_name = 1;</code>
     */
    public int getPackageFqName(int index) {
      return packageFqName_.get(index);
    }
    /**
     * <code>repeated int32 package_fq_name = 1;</code>
     */
    public Builder setPackageFqName(
        int index, int value) {
      ensurePackageFqNameIsMutable();
      packageFqName_.set(index, value);
      
      return this;
    }
    /**
     * <code>repeated int32 package_fq_name = 1;</code>
     */
    public Builder addPackageFqName(int value) {
      ensurePackageFqNameIsMutable();
      packageFqName_.add(value);
      
      return this;
    }
    /**
     * <code>repeated int32 package_fq_name = 1;</code>
     */
    public Builder addAllPackageFqName(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensurePackageFqNameIsMutable();
      org.jetbrains.kotlin.protobuf.AbstractMessageLite.Builder.addAll(
          values, packageFqName_);
      
      return this;
    }
    /**
     * <code>repeated int32 package_fq_name = 1;</code>
     */
    public Builder clearPackageFqName() {
      packageFqName_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      
      return this;
    }

    private java.util.List<java.lang.Integer> classFqName_ = java.util.Collections.emptyList();
    private void ensureClassFqNameIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        classFqName_ = new java.util.ArrayList<java.lang.Integer>(classFqName_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated int32 class_fq_name = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getClassFqNameList() {
      return java.util.Collections.unmodifiableList(classFqName_);
    }
    /**
     * <code>repeated int32 class_fq_name = 2;</code>
     */
    public int getClassFqNameCount() {
      return classFqName_.size();
    }
    /**
     * <code>repeated int32 class_fq_name = 2;</code>
     */
    public int getClassFqName(int index) {
      return classFqName_.get(index);
    }
    /**
     * <code>repeated int32 class_fq_name = 2;</code>
     */
    public Builder setClassFqName(
        int index, int value) {
      ensureClassFqNameIsMutable();
      classFqName_.set(index, value);
      
      return this;
    }
    /**
     * <code>repeated int32 class_fq_name = 2;</code>
     */
    public Builder addClassFqName(int value) {
      ensureClassFqNameIsMutable();
      classFqName_.add(value);
      
      return this;
    }
    /**
     * <code>repeated int32 class_fq_name = 2;</code>
     */
    public Builder addAllClassFqName(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureClassFqNameIsMutable();
      org.jetbrains.kotlin.protobuf.AbstractMessageLite.Builder.addAll(
          values, classFqName_);
      
      return this;
    }
    /**
     * <code>repeated int32 class_fq_name = 2;</code>
     */
    public Builder clearClassFqName() {
      classFqName_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      
      return this;
    }

    // @@protoc_insertion_point(builder_scope:org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId)
  }

  static {
    defaultInstance = new ClassAndPackageId(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId)
}
