// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

public interface FieldAccessCommonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jetbrains.kotlin.backend.common.serialization.proto.FieldAccessCommon)
    org.jetbrains.kotlin.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required int64 symbol = 1;</code>
   *
   * <pre>
   *  required int32 symbol = 1;
   * </pre>
   */
  boolean hasSymbol();
  /**
   * <code>required int64 symbol = 1;</code>
   *
   * <pre>
   *  required int32 symbol = 1;
   * </pre>
   */
  long getSymbol();

  /**
   * <code>optional int64 super = 2;</code>
   *
   * <pre>
   *  optional int32 super = 2;
   * </pre>
   */
  boolean hasSuper();
  /**
   * <code>optional int64 super = 2;</code>
   *
   * <pre>
   *  optional int32 super = 2;
   * </pre>
   */
  long getSuper();

  /**
   * <code>optional .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression receiver = 3;</code>
   */
  boolean hasReceiver();
  /**
   * <code>optional .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression receiver = 3;</code>
   */
  org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression getReceiver();
}