// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

public interface IrFileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jetbrains.kotlin.backend.common.serialization.proto.IrFile)
    org.jetbrains.kotlin.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated int64 declaration_id = 1;</code>
   *
   * <pre>
   *  repeated UniqId declaration_id = 1;
   * </pre>
   */
  java.util.List<java.lang.Long> getDeclarationIdList();
  /**
   * <code>repeated int64 declaration_id = 1;</code>
   *
   * <pre>
   *  repeated UniqId declaration_id = 1;
   * </pre>
   */
  int getDeclarationIdCount();
  /**
   * <code>repeated int64 declaration_id = 1;</code>
   *
   * <pre>
   *  repeated UniqId declaration_id = 1;
   * </pre>
   */
  long getDeclarationId(int index);

  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.FileEntry file_entry = 2;</code>
   */
  boolean hasFileEntry();
  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.FileEntry file_entry = 2;</code>
   */
  org.jetbrains.kotlin.backend.common.serialization.proto.FileEntry getFileEntry();

  /**
   * <code>repeated int32 fq_name = 3;</code>
   */
  java.util.List<java.lang.Integer> getFqNameList();
  /**
   * <code>repeated int32 fq_name = 3;</code>
   */
  int getFqNameCount();
  /**
   * <code>repeated int32 fq_name = 3;</code>
   */
  int getFqName(int index);

  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.Annotations annotations = 4;</code>
   */
  boolean hasAnnotations();
  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.Annotations annotations = 4;</code>
   */
  org.jetbrains.kotlin.backend.common.serialization.proto.Annotations getAnnotations();

  /**
   * <code>repeated int32 explicitly_exported_to_compiler = 5;</code>
   */
  java.util.List<java.lang.Integer> getExplicitlyExportedToCompilerList();
  /**
   * <code>repeated int32 explicitly_exported_to_compiler = 5;</code>
   */
  int getExplicitlyExportedToCompilerCount();
  /**
   * <code>repeated int32 explicitly_exported_to_compiler = 5;</code>
   */
  int getExplicitlyExportedToCompiler(int index);
}