// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

public interface IrGetObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jetbrains.kotlin.backend.common.serialization.proto.IrGetObject)
    org.jetbrains.kotlin.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required int64 symbol = 1;</code>
   *
   * <pre>
   *  required int32 symbol = 1;
   * </pre>
   */
  boolean hasSymbol();
  /**
   * <code>required int64 symbol = 1;</code>
   *
   * <pre>
   *  required int32 symbol = 1;
   * </pre>
   */
  long getSymbol();
}