// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

public interface IrLocalDelegatedPropertyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jetbrains.kotlin.backend.common.serialization.proto.IrLocalDelegatedProperty)
    org.jetbrains.kotlin.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrDeclarationBase base = 1;</code>
   */
  boolean hasBase();
  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrDeclarationBase base = 1;</code>
   */
  org.jetbrains.kotlin.backend.common.serialization.proto.IrDeclarationBase getBase();

  /**
   * <code>required int32 name = 2;</code>
   */
  boolean hasName();
  /**
   * <code>required int32 name = 2;</code>
   */
  int getName();

  /**
   * <code>required int32 type = 3;</code>
   */
  boolean hasType();
  /**
   * <code>required int32 type = 3;</code>
   */
  int getType();

  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrVariable delegate = 4;</code>
   */
  boolean hasDelegate();
  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrVariable delegate = 4;</code>
   */
  org.jetbrains.kotlin.backend.common.serialization.proto.IrVariable getDelegate();

  /**
   * <code>optional .org.jetbrains.kotlin.backend.common.serialization.proto.IrFunction getter = 5;</code>
   */
  boolean hasGetter();
  /**
   * <code>optional .org.jetbrains.kotlin.backend.common.serialization.proto.IrFunction getter = 5;</code>
   */
  org.jetbrains.kotlin.backend.common.serialization.proto.IrFunction getGetter();

  /**
   * <code>optional .org.jetbrains.kotlin.backend.common.serialization.proto.IrFunction setter = 6;</code>
   */
  boolean hasSetter();
  /**
   * <code>optional .org.jetbrains.kotlin.backend.common.serialization.proto.IrFunction setter = 6;</code>
   */
  org.jetbrains.kotlin.backend.common.serialization.proto.IrFunction getSetter();
}