// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

public interface IrLocalDelegatedPropertyReferenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jetbrains.kotlin.backend.common.serialization.proto.IrLocalDelegatedPropertyReference)
    org.jetbrains.kotlin.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required int64 delegate = 1;</code>
   */
  boolean hasDelegate();
  /**
   * <code>required int64 delegate = 1;</code>
   */
  long getDelegate();

  /**
   * <code>optional int64 getter = 2;</code>
   */
  boolean hasGetter();
  /**
   * <code>optional int64 getter = 2;</code>
   */
  long getGetter();

  /**
   * <code>optional int64 setter = 3;</code>
   */
  boolean hasSetter();
  /**
   * <code>optional int64 setter = 3;</code>
   */
  long getSetter();

  /**
   * <code>required int64 symbol = 4;</code>
   */
  boolean hasSymbol();
  /**
   * <code>required int64 symbol = 4;</code>
   */
  long getSymbol();

  /**
   * <code>optional .org.jetbrains.kotlin.backend.common.serialization.proto.IrStatementOrigin origin = 5;</code>
   */
  boolean hasOrigin();
  /**
   * <code>optional .org.jetbrains.kotlin.backend.common.serialization.proto.IrStatementOrigin origin = 5;</code>
   */
  org.jetbrains.kotlin.backend.common.serialization.proto.IrStatementOrigin getOrigin();
}