// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

public interface IrSetVariableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jetbrains.kotlin.backend.common.serialization.proto.IrSetVariable)
    org.jetbrains.kotlin.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required int64 symbol = 1;</code>
   */
  boolean hasSymbol();
  /**
   * <code>required int64 symbol = 1;</code>
   */
  long getSymbol();

  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression value = 2;</code>
   *
   * <pre>
   *  required int32 symbol = 1;
   * </pre>
   */
  boolean hasValue();
  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression value = 2;</code>
   *
   * <pre>
   *  required int32 symbol = 1;
   * </pre>
   */
  org.jetbrains.kotlin.backend.common.serialization.proto.IrExpression getValue();

  /**
   * <code>optional .org.jetbrains.kotlin.backend.common.serialization.proto.IrStatementOrigin origin = 3;</code>
   */
  boolean hasOrigin();
  /**
   * <code>optional .org.jetbrains.kotlin.backend.common.serialization.proto.IrStatementOrigin origin = 3;</code>
   */
  org.jetbrains.kotlin.backend.common.serialization.proto.IrStatementOrigin getOrigin();
}