// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

public interface IrSymbolDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jetbrains.kotlin.backend.common.serialization.proto.IrSymbolData)
    org.jetbrains.kotlin.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrSymbolKind kind = 1;</code>
   */
  boolean hasKind();
  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrSymbolKind kind = 1;</code>
   */
  org.jetbrains.kotlin.backend.common.serialization.proto.IrSymbolKind getKind();

  /**
   * <code>required int32 id_sig = 2;</code>
   *
   * <pre>
   *  required int64 uniq_id_index = 3;
   * </pre>
   */
  boolean hasIdSig();
  /**
   * <code>required int32 id_sig = 2;</code>
   *
   * <pre>
   *  required int64 uniq_id_index = 3;
   * </pre>
   */
  int getIdSig();
}