// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

public interface IrSymbolDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jetbrains.kotlin.backend.common.serialization.proto.IrSymbolData)
    org.jetbrains.kotlin.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrSymbolKind kind = 1;</code>
   */
  boolean hasKind();
  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrSymbolKind kind = 1;</code>
   */
  org.jetbrains.kotlin.backend.common.serialization.proto.IrSymbolKind getKind();

  /**
   * <code>required int64 uniq_id_index = 4;</code>
   */
  boolean hasUniqIdIndex();
  /**
   * <code>required int64 uniq_id_index = 4;</code>
   */
  long getUniqIdIndex();

  /**
   * <code>required bool uniq_id_locality = 5;</code>
   */
  boolean hasUniqIdLocality();
  /**
   * <code>required bool uniq_id_locality = 5;</code>
   */
  boolean getUniqIdLocality();

  /**
   * <code>required int64 top_level_uniq_id_index = 6;</code>
   */
  boolean hasTopLevelUniqIdIndex();
  /**
   * <code>required int64 top_level_uniq_id_index = 6;</code>
   */
  long getTopLevelUniqIdIndex();

  /**
   * <code>required bool top_level_uniq_id_locality = 7;</code>
   */
  boolean hasTopLevelUniqIdLocality();
  /**
   * <code>required bool top_level_uniq_id_locality = 7;</code>
   */
  boolean getTopLevelUniqIdLocality();

  /**
   * <code>repeated int32 fq_name = 8;</code>
   */
  java.util.List<java.lang.Integer> getFqNameList();
  /**
   * <code>repeated int32 fq_name = 8;</code>
   */
  int getFqNameCount();
  /**
   * <code>repeated int32 fq_name = 8;</code>
   */
  int getFqName(int index);

  /**
   * <code>optional .org.jetbrains.kotlin.backend.common.serialization.proto.DescriptorReference descriptor_reference = 9;</code>
   */
  boolean hasDescriptorReference();
  /**
   * <code>optional .org.jetbrains.kotlin.backend.common.serialization.proto.DescriptorReference descriptor_reference = 9;</code>
   */
  org.jetbrains.kotlin.backend.common.serialization.proto.DescriptorReference getDescriptorReference();
}