// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

public interface IrValueParameterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jetbrains.kotlin.backend.common.serialization.proto.IrValueParameter)
    org.jetbrains.kotlin.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrDeclarationBase base = 1;</code>
   */
  boolean hasBase();
  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.IrDeclarationBase base = 1;</code>
   */
  org.jetbrains.kotlin.backend.common.serialization.proto.IrDeclarationBase getBase();

  /**
   * <code>required int32 name = 2;</code>
   */
  boolean hasName();
  /**
   * <code>required int32 name = 2;</code>
   */
  int getName();

  /**
   * <code>required int32 type = 3;</code>
   */
  boolean hasType();
  /**
   * <code>required int32 type = 3;</code>
   */
  int getType();

  /**
   * <code>optional int32 vararg_element_type = 4;</code>
   */
  boolean hasVarargElementType();
  /**
   * <code>optional int32 vararg_element_type = 4;</code>
   */
  int getVarargElementType();

  /**
   * <code>optional int32 default_value = 5;</code>
   */
  boolean hasDefaultValue();
  /**
   * <code>optional int32 default_value = 5;</code>
   */
  int getDefaultValue();
}