// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

public interface PublicIdSignatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature)
    org.jetbrains.kotlin.protobuf.MessageLiteOrBuilder {

  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId container = 1;</code>
   */
  boolean hasContainer();
  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId container = 1;</code>
   */
  org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId getContainer();

  /**
   * <code>optional int64 member_uniq_id = 2;</code>
   */
  boolean hasMemberUniqId();
  /**
   * <code>optional int64 member_uniq_id = 2;</code>
   */
  long getMemberUniqId();

  /**
   * <code>required int64 flags = 3;</code>
   */
  boolean hasFlags();
  /**
   * <code>required int64 flags = 3;</code>
   */
  long getFlags();
}