// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compiler/ir/serialization.common/src/KotlinIr.proto

package org.jetbrains.kotlin.backend.common.serialization.proto;

/**
 * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature}
 */
public final class PublicIdSignature extends
    org.jetbrains.kotlin.protobuf.GeneratedMessageLite implements
    // @@protoc_insertion_point(message_implements:org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature)
    PublicIdSignatureOrBuilder {
  // Use PublicIdSignature.newBuilder() to construct.
  private PublicIdSignature(org.jetbrains.kotlin.protobuf.GeneratedMessageLite.Builder builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private PublicIdSignature(boolean noInit) { this.unknownFields = org.jetbrains.kotlin.protobuf.ByteString.EMPTY;}

  private static final PublicIdSignature defaultInstance;
  public static PublicIdSignature getDefaultInstance() {
    return defaultInstance;
  }

  public PublicIdSignature getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final org.jetbrains.kotlin.protobuf.ByteString unknownFields;
  private PublicIdSignature(
      org.jetbrains.kotlin.protobuf.CodedInputStream input,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    org.jetbrains.kotlin.protobuf.ByteString.Output unknownFieldsOutput =
        org.jetbrains.kotlin.protobuf.ByteString.newOutput();
    org.jetbrains.kotlin.protobuf.CodedOutputStream unknownFieldsCodedOutput =
        org.jetbrains.kotlin.protobuf.CodedOutputStream.newInstance(
            unknownFieldsOutput, 1);
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              subBuilder = container_.toBuilder();
            }
            container_ = input.readMessage(org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(container_);
              container_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            memberUniqId_ = input.readInt64();
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            flags_ = input.readInt64();
            break;
          }
        }
      }
    } catch (org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      try {
        unknownFieldsCodedOutput.flush();
      } catch (java.io.IOException e) {
      // Should not happen
      } finally {
        unknownFields = unknownFieldsOutput.toByteString();
      }
      makeExtensionsImmutable();
    }
  }
  public static org.jetbrains.kotlin.protobuf.Parser<PublicIdSignature> PARSER =
      new org.jetbrains.kotlin.protobuf.AbstractParser<PublicIdSignature>() {
    public PublicIdSignature parsePartialFrom(
        org.jetbrains.kotlin.protobuf.CodedInputStream input,
        org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
        throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
      return new PublicIdSignature(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public org.jetbrains.kotlin.protobuf.Parser<PublicIdSignature> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int CONTAINER_FIELD_NUMBER = 1;
  private org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId container_;
  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId container = 1;</code>
   */
  public boolean hasContainer() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId container = 1;</code>
   */
  public org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId getContainer() {
    return container_;
  }

  public static final int MEMBER_UNIQ_ID_FIELD_NUMBER = 2;
  private long memberUniqId_;
  /**
   * <code>optional int64 member_uniq_id = 2;</code>
   */
  public boolean hasMemberUniqId() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional int64 member_uniq_id = 2;</code>
   */
  public long getMemberUniqId() {
    return memberUniqId_;
  }

  public static final int FLAGS_FIELD_NUMBER = 3;
  private long flags_;
  /**
   * <code>required int64 flags = 3;</code>
   */
  public boolean hasFlags() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required int64 flags = 3;</code>
   */
  public long getFlags() {
    return flags_;
  }

  private void initFields() {
    container_ = org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId.getDefaultInstance();
    memberUniqId_ = 0L;
    flags_ = 0L;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasContainer()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasFlags()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(org.jetbrains.kotlin.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, container_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt64(2, memberUniqId_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt64(3, flags_);
    }
    output.writeRawBytes(unknownFields);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += org.jetbrains.kotlin.protobuf.CodedOutputStream
        .computeMessageSize(1, container_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += org.jetbrains.kotlin.protobuf.CodedOutputStream
        .computeInt64Size(2, memberUniqId_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += org.jetbrains.kotlin.protobuf.CodedOutputStream
        .computeInt64Size(3, flags_);
    }
    size += unknownFields.size();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature parseFrom(
      org.jetbrains.kotlin.protobuf.ByteString data)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature parseFrom(
      org.jetbrains.kotlin.protobuf.ByteString data,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature parseFrom(byte[] data)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature parseFrom(
      byte[] data,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature parseFrom(
      java.io.InputStream input,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature parseDelimitedFrom(
      java.io.InputStream input,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature parseFrom(
      org.jetbrains.kotlin.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature parseFrom(
      org.jetbrains.kotlin.protobuf.CodedInputStream input,
      org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  /**
   * Protobuf type {@code org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature}
   */
  public static final class Builder extends
      org.jetbrains.kotlin.protobuf.GeneratedMessageLite.Builder<
        org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature, Builder>
      implements
      // @@protoc_insertion_point(builder_implements:org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature)
      org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignatureOrBuilder {
    // Construct using org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      container_ = org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId.getDefaultInstance();
      bitField0_ = (bitField0_ & ~0x00000001);
      memberUniqId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      flags_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature getDefaultInstanceForType() {
      return org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature.getDefaultInstance();
    }

    public org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature build() {
      org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature buildPartial() {
      org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature result = new org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.container_ = container_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.memberUniqId_ = memberUniqId_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.flags_ = flags_;
      result.bitField0_ = to_bitField0_;
      return result;
    }

    public Builder mergeFrom(org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature other) {
      if (other == org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature.getDefaultInstance()) return this;
      if (other.hasContainer()) {
        mergeContainer(other.getContainer());
      }
      if (other.hasMemberUniqId()) {
        setMemberUniqId(other.getMemberUniqId());
      }
      if (other.hasFlags()) {
        setFlags(other.getFlags());
      }
      setUnknownFields(
          getUnknownFields().concat(other.unknownFields));
      return this;
    }

    public final boolean isInitialized() {
      if (!hasContainer()) {
        
        return false;
      }
      if (!hasFlags()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        org.jetbrains.kotlin.protobuf.CodedInputStream input,
        org.jetbrains.kotlin.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId container_ = org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId.getDefaultInstance();
    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId container = 1;</code>
     */
    public boolean hasContainer() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId container = 1;</code>
     */
    public org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId getContainer() {
      return container_;
    }
    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId container = 1;</code>
     */
    public Builder setContainer(org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId value) {
      if (value == null) {
        throw new NullPointerException();
      }
      container_ = value;

      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId container = 1;</code>
     */
    public Builder setContainer(
        org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId.Builder builderForValue) {
      container_ = builderForValue.build();

      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId container = 1;</code>
     */
    public Builder mergeContainer(org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId value) {
      if (((bitField0_ & 0x00000001) == 0x00000001) &&
          container_ != org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId.getDefaultInstance()) {
        container_ =
          org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId.newBuilder(container_).mergeFrom(value).buildPartial();
      } else {
        container_ = value;
      }

      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId container = 1;</code>
     */
    public Builder clearContainer() {
      container_ = org.jetbrains.kotlin.backend.common.serialization.proto.ClassAndPackageId.getDefaultInstance();

      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    private long memberUniqId_ ;
    /**
     * <code>optional int64 member_uniq_id = 2;</code>
     */
    public boolean hasMemberUniqId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 member_uniq_id = 2;</code>
     */
    public long getMemberUniqId() {
      return memberUniqId_;
    }
    /**
     * <code>optional int64 member_uniq_id = 2;</code>
     */
    public Builder setMemberUniqId(long value) {
      bitField0_ |= 0x00000002;
      memberUniqId_ = value;
      
      return this;
    }
    /**
     * <code>optional int64 member_uniq_id = 2;</code>
     */
    public Builder clearMemberUniqId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      memberUniqId_ = 0L;
      
      return this;
    }

    private long flags_ ;
    /**
     * <code>required int64 flags = 3;</code>
     */
    public boolean hasFlags() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 flags = 3;</code>
     */
    public long getFlags() {
      return flags_;
    }
    /**
     * <code>required int64 flags = 3;</code>
     */
    public Builder setFlags(long value) {
      bitField0_ |= 0x00000004;
      flags_ = value;
      
      return this;
    }
    /**
     * <code>required int64 flags = 3;</code>
     */
    public Builder clearFlags() {
      bitField0_ = (bitField0_ & ~0x00000004);
      flags_ = 0L;
      
      return this;
    }

    // @@protoc_insertion_point(builder_scope:org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature)
  }

  static {
    defaultInstance = new PublicIdSignature(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:org.jetbrains.kotlin.backend.common.serialization.proto.PublicIdSignature)
}
